/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package master;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import koneksi.Database;

/**
 *
 * @author Red Dragonize
 */
public class user_manage extends javax.swing.JFrame {
    
Database dbsetting;//---1
String driver, database, user, pass, userlogin;//--2

    /**
     * Creates new form FORM_USERMANAGE
     */
    public user_manage() {
        initComponents();
        
        Database kn = new Database();
        driver= kn.DBDriver;
        database= kn.DBDatabase;
        user = kn.DBUsername;
        pass = kn.DBPassword;
       
        SetEditOff();
        showTable();
        
        //------------------------- Form Posisi Tengah --------------------------//   
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (dim.width-getWidth())/2;
        int y = (dim.height-getHeight())/2;
        setLocation(x, y);
     //-----------------------------------------------------------------------//
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        lbl_iduser = new javax.swing.JLabel();
        Pelanggan = new javax.swing.JCheckBox();
        Belanja = new javax.swing.JCheckBox();
        Jenis_Cuci = new javax.swing.JCheckBox();
        Laporan = new javax.swing.JCheckBox();
        Utility = new javax.swing.JCheckBox();
        Transaksi = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btn_new = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("USER MANAGE");
        setUndecorated(true);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 0, 51));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USER MANAGE CONTROL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(384, 384, 384)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 0, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID User");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");

        txt_nama.setBackground(new java.awt.Color(199, 180, 213));
        txt_nama.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txt_nama.setForeground(new java.awt.Color(255, 255, 255));

        txt_password.setBackground(new java.awt.Color(199, 180, 213));
        txt_password.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txt_password.setForeground(new java.awt.Color(255, 255, 255));

        lbl_iduser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_iduser.setForeground(new java.awt.Color(255, 255, 255));

        Pelanggan.setBackground(new java.awt.Color(204, 204, 204));
        Pelanggan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Pelanggan.setForeground(new java.awt.Color(255, 255, 255));
        Pelanggan.setText("Data Pelanggan");

        Belanja.setBackground(new java.awt.Color(204, 204, 204));
        Belanja.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Belanja.setForeground(new java.awt.Color(255, 255, 255));
        Belanja.setText("Belanja");

        Jenis_Cuci.setBackground(new java.awt.Color(204, 204, 204));
        Jenis_Cuci.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Jenis_Cuci.setForeground(new java.awt.Color(255, 255, 255));
        Jenis_Cuci.setText("Jenis Cuci");

        Laporan.setBackground(new java.awt.Color(204, 204, 204));
        Laporan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Laporan.setForeground(new java.awt.Color(255, 255, 255));
        Laporan.setText("Laporan");
        Laporan.setNextFocusableComponent(btn_save);

        Utility.setBackground(new java.awt.Color(204, 204, 204));
        Utility.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Utility.setForeground(new java.awt.Color(255, 255, 255));
        Utility.setText("Utility");
        Utility.setNextFocusableComponent(btn_save);

        Transaksi.setBackground(new java.awt.Color(204, 204, 204));
        Transaksi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Transaksi.setForeground(new java.awt.Color(255, 255, 255));
        Transaksi.setText("Transaksi");
        Transaksi.setNextFocusableComponent(btn_save);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_iduser, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txt_password, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Pelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Jenis_Cuci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Belanja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Laporan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Utility, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Transaksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(txt_nama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lbl_iduser, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Pelanggan)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jenis_Cuci)
                            .addComponent(Laporan))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Belanja)
                            .addComponent(Utility)))
                    .addComponent(Transaksi))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 0, 51));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cari User");

        txt_cari.setBackground(new java.awt.Color(199, 180, 213));
        txt_cari.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txt_cari.setForeground(new java.awt.Color(255, 255, 255));
        txt_cari.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_cariCaretUpdate(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 0, 51));

        btn_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/new.png"))); // NOI18N
        btn_new.setText("New");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/save.png"))); // NOI18N
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png"))); // NOI18N
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh.png"))); // NOI18N
        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit (1).png"))); // NOI18N
        btn_exit.setText("Exit");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_new)
                .addGap(18, 18, 18)
                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_new)
                    .addComponent(btn_save)
                    .addComponent(btn_edit)
                    .addComponent(btn_delete)
                    .addComponent(btn_refresh)
                    .addComponent(btn_exit))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //--------------------------- Database Showtabel -------------------------//
    public  void showTable(){
       table.setModel(tblModel); 
       String data[]= new String [9];
       String stat = "";
       try {
           Class.forName(driver);
           try(Connection kon = DriverManager.getConnection(database,user,pass);
              Statement stt = kon.createStatement()){
              String SQL ="Select * From user_manage where id_user like '%"+txt_cari.getText()+"%' or username like '%"+txt_cari.getText()+"%' order by id_user desc";
              ResultSet res = stt.executeQuery(SQL);
              while(res.next()){
                  data[0]= res.getString(1);
                  data[1]= res.getString(2);
                  data[2]= res.getString(3);
                  data[3]= res.getString(4);
                  data[4]= res.getString(5);
                  data[5]= res.getString(6);
                  data[6]= res.getString(7);
                  data[7]= res.getString(8);
                  data[8]= res.getString(9);
                  tblModel.addRow(data);
             }
              res.close();
              stt.close();
             }
       } catch(Exception exc){
          System.err.println(exc.getMessage());
       }
 }
    //------------------------------------------------------------------------//
    
    //-------------------------- Default Tabel -------------------------------//
    private javax.swing.table.DefaultTableModel getDefaultTabelModel(){
        return new javax.swing.table.DefaultTableModel(
                new Object [][]{},
                new String [] {"IDUser","Nama","Password","Pelanggan","Jenis","Belanja","Transaksi","Laporan","Utility"}){
                public boolean isCellEditable(int rowIndex, int columnIndex){
                    return false;
            }
                };
    }
    
    // Membersihkan Data ke posisi kosong ------------------------------------//
      private void bersih(){
      this.lbl_iduser.setText(""); 
      this.txt_password.setText("");
      this.txt_nama.setText("");
      this.txt_cari.setText("");
      Pelanggan.setSelected(false);
      Laporan.setSelected(false);
      Jenis_Cuci.setSelected(false);
      Transaksi.setSelected(false);
      Belanja.setSelected(false);
      Utility.setSelected(false);
       }
    
     //-----------------------------------------------------------------------//
      
      //------------------------------ Set Edit OFF ---------------------------//
        public void SetEditOff(){
        lbl_iduser.setEnabled(false);
        txt_nama.setEnabled(false);
        txt_password.setEnabled(false);
        Utility.setEnabled(false);
        Pelanggan.setEnabled(false);
        Laporan.setEnabled(false);
        Jenis_Cuci.setEnabled(false);
        Belanja.setEnabled(false);
        Transaksi.setEnabled(false);
        btn_save.setEnabled(false);
        btn_edit.setEnabled(false);
        btn_delete.setEnabled(false);
    }
    //------------------------------------------------------------------------//
    
    //------------------------------ Set Edit ON -----------------------------//
        public void SetEditOn(){
        lbl_iduser.setEnabled(true);
        txt_nama.setEnabled(true);
        txt_password.setEnabled(true);
        Pelanggan.setEnabled(true);
        Laporan.setEnabled(true);
        Jenis_Cuci.setEnabled(true);
         Transaksi.setEnabled(true);
        Belanja.setEnabled(true);
        Utility.setEnabled(true);
        btn_save.setEnabled(true);
        btn_edit.setEnabled(true);
        btn_delete.setEnabled(true);
    }
    //------------------------------------------------------------------------//
        
    //---------------------------- NO USER OTOMATIS --------------------------//  
    private void id_user()
    {
        int byk_data;
        byk_data = 0;
        try
        {
            Connection kon = DriverManager.getConnection(database,user,pass);
            String sql = "select * from user_manage order by id_user";
            Statement stat = kon.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            rs.last();
            byk_data = rs.getRow();
            if (byk_data == 0)
                {
                this.lbl_iduser.setText("U01");
                }
            else
                {
                String id = rs.getString(1);
                int n = Integer.parseInt(id.substring(1, 3)) + 1;
                String nomor = "";
                for(int i = 1; i <= 2 - String.valueOf(n).length(); i++)
                {
                    nomor = nomor + "0";
                }
                nomor = "U" + nomor + String.valueOf(n);
                this.lbl_iduser.setText(nomor);
                }
        }
        catch (Exception e)
        {
        System.out.println("Error auto increment userID : " + e + "\n");
        }
        }
    
    //------------------------------------------------------------------------//
    
    //--------------------------- Input Valid --------------------------------//
    private boolean inputValid() {
        boolean result;
        if ((txt_nama.getText().equals("")) || (txt_password.getText().equals("")) ) {
            JOptionPane.showMessageDialog(null, "Isi data yang dibutuhkan");
            result = false;
        } else {
            result = true;
        }
        return result;

    }
    //------------------------------------------------------------------------//
    
    //-------------------------- Method Tampil -------------------------------//
    int row = 0;
    public void Tampil() {
        row = table.getSelectedRow();
        lbl_iduser.setText(tblModel.getValueAt(row, 0).toString());
        txt_nama.setText(tblModel.getValueAt(row, 1).toString());
//        txt_password.setText(tblModel.getValueAt(row, 2).toString());

        if (tblModel.getValueAt(row, 3).toString().equals("1")) {
            Pelanggan.setSelected(true);
        } else {
            Pelanggan.setSelected(false);
            
        }

        if (tblModel.getValueAt(row, 4).toString().equals("1")) {
            Jenis_Cuci.setSelected(true);
        } else {
            Jenis_Cuci.setSelected(false);
            
        }
        
        if (tblModel.getValueAt(row, 5).toString().equals("1")) {
            Belanja.setSelected(true);
        } else {
            Belanja.setSelected(false);
        }
        
        if (tblModel.getValueAt(row, 6).toString().equals("1")) {
            Transaksi.setSelected(true);
        } else {
            Transaksi.setSelected(false);
        }
        
        if (tblModel.getValueAt(row, 7).toString().equals("1")) {
            Laporan.setSelected(true);
        } else {
            Laporan.setSelected(false);
        }

        if (tblModel.getValueAt(row, 8).toString().equals("1")) {
            Utility.setSelected(true);
        } else {
            Utility.setSelected(false);
        }

        
        
        
    }
    //------------------------------------------------------------------------//
    
    //------------------------ Refresh Tabel --------------------------------//
    
        private void KosongkanTabel() {
        int brs1 = tblModel.getRowCount();
        for (int i = 0; i < brs1; i++) {
            tblModel.removeRow(0);
        }
    }
    //------------------------------------------------------------------------//
        
    // Refresh Tabel & kolom - kolom -----------------------------------------//
    public void RefreshTabel(){
    int brs = tblModel.getRowCount();
    for (int i=0;i<brs;i++){
    tblModel.removeRow(0);
  }
  }
    //------------------------------------------------------------------------//
    
    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        bersih();
        dispose();
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        bersih();
        id_user();
        SetEditOn();
        txt_nama.requestFocus();
        btn_edit.setEnabled(false);
        btn_delete.setEnabled(false);
        btn_save.setEnabled(true);
    }//GEN-LAST:event_btn_newActionPerformed

    private void txt_cariCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_cariCaretUpdate
        RefreshTabel();
        showTable();
    }//GEN-LAST:event_txt_cariCaretUpdate

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
         if (inputValid() == true) {

            try {

                String pelanggan = "", jenis = "", belanja = "" ,  transaksi= "" ,laporan= "",utility= "";
                if (Pelanggan.isSelected()) {
                    pelanggan = "1";
                } else {
                    pelanggan = "0";
                }

                if (Jenis_Cuci.isSelected()) {
                    jenis = "1";
                } else {
                    jenis = "0";
                }
                
                if (Belanja.isSelected()) {
                    belanja = "1";
                } else {
                    belanja = "0";
                }
                
                if (Transaksi.isSelected()) {
                    transaksi = "1";
                } else {
                    transaksi = "0";
                }
                
                if (Laporan.isSelected()) {
                    laporan = "1";
                } else {
                    laporan = "0";
                }
                
                if (Utility.isSelected()) {
                    utility = "1";
                } else {
                    utility = "0";
                }

                Class.forName(driver);
                Connection kon = DriverManager.getConnection(database, user, pass);
                Statement stt = kon.createStatement();
                String SQL = "insert into user_manage values ('" + lbl_iduser.getText()
                        + "','" + txt_nama.getText()
                        + "',md5('" + txt_password.getText()
                        + "'),'" + pelanggan
                        + "','" + jenis
                        + "','" + belanja
                        + "','" + transaksi
                        + "','" + laporan
                        + "','" + utility
                        + "')";
                stt.executeUpdate(SQL);
                stt.close();
                kon.close();
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            } catch (Exception exc) {
                JOptionPane.showMessageDialog(null, "Peringatan !!! Terjadi Duplikasi Data ");
                System.err.println(exc.getMessage());
            }
        }

        RefreshTabel();
        bersih();
        showTable();
        SetEditOff();
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        if (inputValid() == true) {

            try {

                String pelanggan = "", jenis = "", belanja = "", transaksi= "" ,laporan= "",utility= "";
                if (Pelanggan.isSelected()) {
                    pelanggan = "1";
                } else {
                    pelanggan = "0";
                }

                if (Jenis_Cuci.isSelected()) {
                    jenis = "1";
                } else {
                    jenis = "0";
                }
                
                if (Belanja.isSelected()) {
                    belanja = "1";
                } else {
                    belanja = "0";
                }
                
                if (Transaksi.isSelected()) {
                    transaksi = "1";
                } else {
                    transaksi = "0";
                }
                
                if (Laporan.isSelected()) {
                    laporan = "1";
                } else {
                    laporan = "0";
                }
                
                if (Utility.isSelected()) {
                    utility = "1";
                } else {
                    utility = "0";
                }

                Class.forName(driver);
                Connection kon = DriverManager.getConnection(database, user, pass);
                Statement stt = kon.createStatement();
                String SQL = "update user_manage set username='" + txt_nama.getText()
                        + "',password=md5('" + txt_password.getText()
                        + "'),pelanggan='" + pelanggan
                        + "',jenis='" + jenis
                        + "',belanja='" + belanja
                        + "',transaksi='" + transaksi
                        + "',laporan='" + laporan
                        + "',utility='" + utility
                        + "' where id_user='" + lbl_iduser.getText() + "'";
                stt.executeUpdate(SQL);
                stt.close();
                kon.close();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            } catch (Exception exc) {
                JOptionPane.showMessageDialog(null, "Peringatan !!! Cek Kembali Data Inputan ");
                System.err.println(exc.getMessage());
            }
        }
        RefreshTabel();
        bersih();
        showTable();
        SetEditOff();
        btn_new.setEnabled(true);
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
            try {
                Class.forName(driver);
                Connection kon = DriverManager.getConnection(database, user, pass);
                Statement stt = kon.createStatement();
                String SQL = "Delete from user_manage where id_user ='" + lbl_iduser.getText() + "' ";
                stt.executeUpdate(SQL);
                stt.close();
            } catch (Exception exc) {
                System.err.println(exc.getMessage());
            }
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            RefreshTabel();
            bersih();
            showTable();
            SetEditOff();
            btn_new.setEnabled(true);
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        if (evt.getClickCount() == 2) {
            Tampil();
            lbl_iduser.setEnabled(true);
            txt_nama.setEnabled(true);
            txt_password.setEnabled(true);
            Pelanggan.setEnabled(true);
            Laporan.setEnabled(true);
            Jenis_Cuci.setEnabled(true);
            Transaksi.setEnabled(true);
            Belanja.setEnabled(true);
            Utility.setEnabled(true);
            btn_edit.setEnabled(true);
            btn_delete.setEnabled(true);
            btn_new.setEnabled(false);
            btn_save.setEnabled(false);
        }
    }//GEN-LAST:event_tableMouseClicked

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        bersih();
        SetEditOff();
        btn_new.setEnabled(true);
    }//GEN-LAST:event_btn_refreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new user_manage().setVisible(true);
            }
        });
    }
    private javax.swing.table.DefaultTableModel tblModel = getDefaultTabelModel();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Belanja;
    private javax.swing.JCheckBox Jenis_Cuci;
    private javax.swing.JCheckBox Laporan;
    private javax.swing.JCheckBox Pelanggan;
    private javax.swing.JCheckBox Transaksi;
    private javax.swing.JCheckBox Utility;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_iduser;
    private javax.swing.JTable table;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JPasswordField txt_password;
    // End of variables declaration//GEN-END:variables
}
